/**
 * @mcp-web/app - Build tooling for MCP Apps
 *
 * This package provides tools for creating MCP Apps - visual UI components
 * that AI agents can render inline in chat interfaces like Claude Desktop.
 *
 * ## Main Exports
 *
 * - `createApp` - Define an app with a handler and component
 *
 * ## Vite Plugin (via `@mcp-web/app/vite`)
 *
 * - `defineMCPAppsConfig` - Create a Vite config for building MCP Apps
 *
 * ## Host Theming
 *
 * MCP Apps automatically inherit the host's theme. Use these hooks to access
 * the host's theme and context in your components:
 *
 * - `useMCPHostTheme` - Get the current host theme (`"light"` or `"dark"`)
 * - `useMCPHostContext` - Get the full host context (theme, display mode, locale, etc.)
 *
 * ## Advanced Exports
 *
 * - `renderMCPApp` - Manually render a component (auto-generated by Vite plugin)
 * - `useMCPAppProps` - React hook for custom prop handling
 * - `useMCPApp` - Access the ext-apps `App` instance
 * - `MCPAppProvider` - Context provider (set up automatically by renderMCPApp)
 *
 * @example Define an MCP App (src/mcp-apps.ts)
 * ```typescript
 * import { createApp } from '@mcp-web/app';
 * import { Statistics } from './components/Statistics';
 *
 * export const statsApp = createApp({
 *   name: 'show_stats',
 *   description: 'Display statistics visualization',
 *   component: Statistics,
 *   handler: () => ({
 *     completionRate: 0.75,
 *     totalTasks: 100,
 *   }),
 * });
 * ```
 *
 * @example Build Config (vite.apps.config.ts)
 * ```typescript
 * import react from '@vitejs/plugin-react';
 * import { defineMCPAppsConfig } from '@mcp-web/app/vite';
 *
 * // Automatically discovers apps in src/mcp-apps.ts
 * export default defineMCPAppsConfig({
 *   plugins: [react()],
 * });
 * ```
 *
 * @example Register with MCPWeb (in your app)
 * ```typescript
 * import { statsApp } from './mcp-apps';
 *
 * mcp.addApp(statsApp);
 * ```
 *
 * @packageDocumentation
 */

export { createApp, isCreatedApp } from './create-app.js';
export type { CreateAppConfig, CreatedApp } from './create-app.js';

export {
  useMCPAppProps,
  useMCPApp,
  getMCPAppProps,
  subscribeMCPAppProps,
} from './use-mcp-app-props.js';

export {
  MCPAppProvider,
  useMCPHostContext,
  useMCPHostTheme,
} from './mcp-app-context.js';
export type { MCPAppContextValue } from './mcp-app-context.js';

export { renderMCPApp } from './render-mcp-app.js';
export type { RenderMCPAppOptions } from './render-mcp-app.js';

export { useDocumentTheme } from '@modelcontextprotocol/ext-apps/react';
