packages:
  - demos/*
  - demos/*/app
  - demos/*/agent
  - demos/*/bridge
  - demos/*/shared
  - docs
  - packages/*
  - packages/integrations/*
  - tests

catalog:
  '@modelcontextprotocol/sdk': ^1.15.1
  '@types/node': ^24.10.1
  ajv: ^8.17.1
  tsx: ^4.20.6
  typescript: ~5.9.3
  zod: ~4.1.12

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
