packages:
  - demos/*
  - demos/*/app
  - demos/*/agent
  - demos/*/bridge
  - demos/*/shared
  - docs
  - packages/*
  - packages/integrations/*
  - tests

catalog:
  '@modelcontextprotocol/sdk': ^1.15.1
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.0.9
  ajv: ^8.17.1
  jotai: ^2.10.3
  tailwindcss: ^4.1.18
  tsx: ^4.20.6
  typescript: ~5.9.3
  vite: ^7.3.1
  zod: ~4.1.12

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
